name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      T_1: dckr_pat_HD7GK-gw
      T_2: go6r93Jdn5R4A1KvP0g
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: angaadmallick
          password: ${{ env.T_1 }}${{ env.T_2 }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inventoryos-backend:latest
