name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "ZGNrcl9wYXRfSEQ3R0stZ3dnbzZyOTNKZG41UjRBMUt2UDBn" | base64 --decode | docker login -u angaadmallick --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/inventoryos-backend:latest
